Update postinst script

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -21,8 +21,11 @@ case "$1" in
         su shinken -c 'git commit -a -m "Initial Kaji installation commit"'
     fi
 #    a2ensite adagios
-    service apache2 restart || "Failed to restart Apache2. You have to restart Apache2 to update its configuration"
-    service shinken restart || "Failed to restart Shinken. You have to restart Shinken to update its configuration"
+    service shinken restart || echo "Failed to restart Shinken. You have to restart Shinken to update its configuration"
+    service apache2 reload || echo "Failed to restart Apache2. You have to restart Apache2 to update its configuration"
+    echo
+    echo "Kaji install finished"
+    echo
     ;;
   abort-upgrade)
     # Back out of an attempt to upgrade this package FROM THIS VERSION
